export const GET_TRANSCRIPT_REQUEST = 'GET_TRANSCRIPT_REQUEST';
export const GET_TRANSCRIPT_SUCCESS = 'GET_TRANSCRIPT_SUCCESS';
export const GET_TRANSCRIPT_FAILED = 'GET_TRANSCRIPT_FAILED';

export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_FAILED = 'GET_STUDENT_FAILED'
